spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001 #注册中心占用8001端口号，冒号后面必须有空格

spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource        
  driver-class-name: com.mysql.cj.jdbc.Driver          
  url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC          
  username: root
  password: 123456
  dbcp2:
   min-idle: 5                                        
   initial-size: 5                                    
   max-total: 5                                       
   max-wait-millis: 200                               

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.weifu.springcloud.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
     
  instance:
    instance-id: dept-8001.com  
    prefer-ip-address: true       

info:
  app.name: weifu-microservicecloud-springcloudconfig01
  company.name: www.weifu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001 #注册中心占用8002端口号，冒号后面必须有空格

spring:
  profiles: test  #开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource        
  driver-class-name: com.mysql.cj.jdbc.Driver          
  url: jdbc:mysql://localhost:3306/clouddb02?serverTimezone=UTC          
  username: root
  password: 123456
  dbcp2:
   min-idle: 5                                        
   initial-size: 5                                    
   max-total: 5                                       
   max-wait-millis: 200                               

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.weifu.springcloud.entities   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
     
  instance:
    instance-id: dept-8001.com  
    prefer-ip-address: true       

info:
  app.name: weifu-microservicecloud-springcloudconfig01
  company.name: www.weifu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$